### ISSUE TITLE
リクエストページにマナーの追記

### ISSUE THREAD

**Issue by youmjww** [mikankari/bgmshare4#15]
極稀にネタに走った曲をリクエストする人がいる。
TPO的に大丈夫か一度考えてほしいので、わかりやすいところに注意書きを書くと良いと思うという提案

**Comment by mikankari** [comment]
提案ありがとう！
懸念があるとするとこれはオープンソースの品なので、他所で使うことを想定しています。
提案はローカルルールなので、ローカルな docbase に書くか IP で表示を振り分けるかになるかな。

**Comment by youmjww** [comment]
運用の問題なので、改修は行わないということで承知！
本issuesはクローズします。
