### ISSUE TITLE
特定の動画の削除機能の提案

### ISSUE THREAD

**Issue by youmjww** [mikankari/bgmshare4#17]
# 問題

現状の仕様だと、明らかに問題のある動画が入っている場合、システム管理者に依頼を出さないと特定の動画の削除を行えない

# 解決策

画面に削除ボタンを追加し、誰かが流石にこの動画はダメだろと思うと削除出来るようにする

**Comment by mikankari** [comment]
ありがとう！

仕様メモ
キューにゴミ箱アイコンのリンクを置いて、リンク先で queue からインデックス・url が一致するものを削除する

**Comment by mikankari** [comment]
> playing object にuniq() みたいな ID を入れて、この ID のものを削除のほうがいいかも、と思いつく

完了しました。
